Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -2,13 +2,13 @@ name: Compile LaTeX and Create Release
 
 on:
   push:
-    branches: [ master ]  # Adjust this if your main branch has a different name
+    branches: [ master ]  
 
 jobs:
-  build_latex:
+  compile_latex:
     runs-on: ubuntu-latest
     steps:
-      - name: Set up Git repository
+      - name: Checkout repository
         uses: actions/checkout@v2
 
       - name: Compile LaTeX document
@@ -17,6 +17,25 @@ jobs:
           root_file: main.tex  # Replace with your main .tex file name
           latexmk_use_xelatex: true
 
+      - name: Check for PDF
+        run: |
+          if [ -f "main.pdf" ]; then
+            echo "PDF file found"
+          else
+            echo "PDF file not found"
+            exit 1
+          fi
+
+      - name: Upload PDF artifact
+        uses: actions/upload-artifact@v2
+        with:
+          name: resume-pdf
+          path: main.pdf
+
+  create_release:
+    needs: compile_latex
+    runs-on: ubuntu-latest
+    steps:
       - name: Get current date
         id: date
         run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
@@ -31,13 +50,24 @@ jobs:
           release_name: Release ${{ steps.date.outputs.date }}
           draft: false
           prerelease: false
+    outputs:
+      upload_url: ${{ steps.create_release.outputs.upload_url }}
+
+  upload_asset:
+    needs: [compile_latex, create_release]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download PDF artifact
+        uses: actions/download-artifact@v2
+        with:
+          name: resume-pdf
 
       - name: Upload Release Asset
         uses: actions/upload-release-asset@v1
         env:
           GITHUB_TOKEN: ${{ secrets.PAT }}
         with:
-          upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ./main.pdf  # This should be the path to your generated PDF
-          asset_name: Pushpinder_Resume.pdf  # This will be the name of the file in the release
+          upload_url: ${{ needs.create_release.outputs.upload_url }}
+          asset_path: ./main.pdf
+          asset_name: Pushpinder_Resume.pdf
           asset_content_type: application/pdf
